### ISSUE TITLE
Bootstrap 4 'media-breakpoint-up' behavior support

### ISSUE THREAD

**Issue by ghost** [keenondrums/angular-responsive-breakpoints#5]
Hi Andrey, nice lib

But I needed it to play more like Bootstrap 4 media-breakpoint-up mixin (https://getbootstrap.com/docs/4.1/layout/overview/#responsive-breakpoints), which has reverse check of breakpoints (e.g. `md` is 768 and it's check is >= 768 and < 992, and some other tweaks. So I created my fork for that, and just wanted to mention that to you - in case you also want to update your lib the same way.

Sorry, I did not do a PR, because not sure if you actually want that change, so just link to my changes: https://github.com/antivitla/angular-responsive-breakpoints/commits/master

**Comment by fxlrnrpt** [comment]
@antivitla it seems you could've used a different condition to achieve what you wanted
```
xsGt && !smGt
```
would check for > 600 and <= 960

Anyway thanks for keeping me in the loop
